table fct_debt

	column record_date
		dataType: dateTime
		isDefaultLabel
		formatString: yyyy-mm-dd
		summarizeBy: none
		sourceColumn: record_date

		annotation SummarizationSetBy = Automatic

	column total_public_debt
		dataType: decimal
		formatString: "$" #,##0.0,,
		summarizeBy: sum
		sourceColumn: total_public_debt

		annotation SummarizationSetBy = Automatic

	column debt_held_public
		dataType: decimal
		formatString: "$" #,##0.0,,
		summarizeBy: sum
		sourceColumn: debt_held_public

		annotation SummarizationSetBy = Automatic

	column intragov_held
		dataType: decimal
		formatString: "$" #,##0.0,,
		summarizeBy: sum
		sourceColumn: intragov_held

		annotation SummarizationSetBy = Automatic

	measure 'Total Public Debt' = MAX(fct_debt[total_public_debt])
		formatString: "$" #,##0.0,,

	measure 'Debt Held by the Public' = MAX(fct_debt[debt_held_public])
		formatString: "$" #,##0.0,,

	partition fct_debt = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents(DataFolder & "debt_to_penny.csv"),[Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Renamed" = Table.RenameColumns(#"Promoted Headers",{{"tot_pub_debt_out_amt", "total_public_debt"}, {"debt_held_public_amt", "debt_held_public"}, {"intragov_hold_amt", "intragov_held"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed",{{"record_date", Date.Type}, {"total_public_debt", Currency.Type}, {"debt_held_public", Currency.Type}, {"intragov_held", Currency.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
