table fct_agency_obligations

	column code
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: code

		annotation SummarizationSetBy = Automatic
		annotation PBI_ChangedProperties = ["IsHidden"]

	column fiscal_year
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: fiscal_year

		annotation SummarizationSetBy = Automatic

	column period
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: period

		annotation SummarizationSetBy = Automatic
		annotation PBI_ChangedProperties = ["IsHidden"]

	column obligated
		dataType: decimal
		formatString: "$" #,##0.0,,
		summarizeBy: sum
		sourceColumn: obligated

		annotation SummarizationSetBy = Automatic

	measure 'Obligated YTD' = MAX(fct_agency_obligations[obligated])
		formatString: "$" #,##0.0,,

	measure 'Obligated FYE (last actual)' = CALCULATE([Obligated YTD], ALL(dim_period))
		formatString: "$" #,##0.0,,

	measure 'Period Delta' = VAR curPeriod = MAX(fct_agency_obligations[period]) RETURN [Obligated YTD] - CALCULATE([Obligated YTD], ALL(dim_period), dim_period[period] = curPeriod - 1)
		formatString: "$" #,##0.0,,

	partition fct_agency_obligations = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents(DataFolder & "agency_obligation_by_period.csv"),[Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"code", type text}, {"fiscal_year", Int64.Type}, {"period", Int64.Type}, {"obligated", Currency.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
